### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by yeshymanoharan** [ARMmbed/littlefs-fuse#12]
Compiling the program with 'make' once littlefs-fuse has been cloned leads to this error:
> lfs_fuse.c:15:23: fatal error: fuse/fuse.h: No such file or directory

My fusermount version is 2.9.4, which means that the fuse header file should be available, right?

**Comment by geky** [comment]
Hmmm, it looks like you might need the package "libfuse-dev":
```
sudo apt-get install libfuse-dev
```

Assuming you're using Ubuntu/Debian, what distro are you using?

I'm surprised I haven't noticed this requirement before.

**Comment by yeshymanoharan** [comment]
Thanks, that did the trick!

I'm using Ubuntu 16.04.4 LTS (GNU/Linux 4.13.0-45-generic x86_64)

**Comment by geky** [comment]
Ah! Good to know. Here I'll add a note about this: https://github.com/ARMmbed/littlefs-fuse/pull/13
