### ISSUE TITLE
MbedOS lfs and littlefs-fuse - corrupted dir pair at 0 1

### ISSUE THREAD

**Issue by sergiuszm** [ARMmbed/littlefs-fuse#21]
Hello,

I have tried to use littlefs-fuse to read data from a SD card that uses littlefs. My first approach was to use mbed-os-example-filesystem with SDBlockDevice as a BlockDevice for littlefs. The code works correctly on the micricontroller. However, I am not able to mount the SD card in Linux using littlefs-fuse. I am getting the following error:
```
./lfs /dev/sdb mount
lfs error:969: Corrupted dir pair at 0 1
lfs error:514: Invalid or incomplete multibyte or wide character
```

I have tried to reformat the SD card with littlefs-fuse and then use in in the microcontroller. Unfortunately I am getting the same error but this time it is littlefs from MbedOS that complains:
```
Mounting the filesystem... 
lfs error:493: Corrupted dir pair at 0 1
lfs error:2216: Invalid superblock at 0 1
Fail :(
No filesystem found, formatting... OK
```

I am using MbedOS 5.15.0 and littlefs-fuse build from this repository.

**Comment by danielnegris** [comment]
If you're using non-standard block size (32k) or another parameter you have to specify those when using mount: 
./lfs --block_size=BLOCK_SIZE /dev/sdb mount.

You can also try to use --migrate to migrate to a previous littlefs version.

**Comment by geky** [comment]
Ah, you may need the v1 branch:
https://github.com/ARMmbed/littlefs-fuse/tree/v1

Mbed OS is still using v1 unless you've explicitly added the v2 repo and are using LittleFileSystem2 in your project:
https://github.com/armmbed/mbed-littlefs

@danielnegris is right that you _can_ use --migrate to convert a filesystem from v1 to v2, however this is a bad thing if your MCU is using v1, you won't be able to mount it on the MCU.

**Comment by sergiuszm** [comment]
@danielnegris That is not a case - I am using standard parameters :)

@geky You are right. I have not noticed that MbesOS is using v1 while littlefs-fuse uses v2. My bad but thanks a lot for help!

**Comment by isaev-d** [comment]
I think that thread should be part of documentation for arm mbed littlefs example.

**Comment by geky** [comment]
Actually, since this issue, Mbed OS has adopted v2. So hopefully this issue will be less likely to be hit.
https://github.com/ARMmbed/mbed-os/pull/12783
