### ISSUE TITLE
Compilation error on recent Fedora system

### ISSUE THREAD

**Issue by armijnhemel** [ARMmbed/littlefs-fuse#8]
I tried to compile according to the instructions, but no luck:

$ make
cc -c -MMD -Os -I. -Ilittlefs -std=c99 -Wall -pedantic -D_FILE_OFFSET_BITS=64 -D_XOPEN_SOURCE=700 lfs_fuse_bd.c -o lfs_fuse_bd.o
lfs_fuse_bd.c:15:10: fatal error: stropts.h: No such file or directory
 #include <stropts.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:51: lfs_fuse_bd.o] Error 1

Apparently stropts.h has not been distributed in Fedora for about a decade, so probably it should be removed.

**Comment by geky** [comment]
Ah interesting, it looks like this was bringing in ioctl on Linux. It looks like "sys/ioctl.h" should be the correct path.

Does this work for you? https://github.com/ARMmbed/littlefs-fuse/pull/11
