### ISSUE TITLE
compilation error: test.c interfering

### ISSUE THREAD

**Issue by armijnhemel** [ARMmbed/littlefs-fuse#9]
hello,

the file "test.c" in the littlefs directory is interfering with compilation:

$ make
cc -Os -I. -Ilittlefs -std=c99 -Wall -pedantic -D_FILE_OFFSET_BITS=64 -D_XOPEN_SOURCE=700 lfs_fuse_bd.o lfs_fuse.o littlefs/lfs_util.o littlefs/test.o littlefs/lfs.o -lfuse -o lfs
littlefs/test.o: In function `main':
test.c:(.text.startup+0x0): multiple definition of `main'
lfs_fuse.o:lfs_fuse.c:(.text.startup+0x0): first defined here
littlefs/test.o: In function `main':
test.c:(.text.startup+0x23): undefined reference to `lfs_emubd_create'
test.c:(.text.startup+0x1ed): undefined reference to `lfs_emubd_destroy'
littlefs/test.o:(.rodata+0x8): undefined reference to `lfs_emubd_read'
littlefs/test.o:(.rodata+0x10): undefined reference to `lfs_emubd_prog'
littlefs/test.o:(.rodata+0x18): undefined reference to `lfs_emubd_erase'
littlefs/test.o:(.rodata+0x20): undefined reference to `lfs_emubd_sync'
collect2: error: ld returned 1 exit status
make: *** [Makefile:45: lfs] Error 1

The problem is that littlefs/test.c has a main(), as does lfs_fuse.c

Removing littlefs/test.c fixes the issue.

**Comment by geky** [comment]
Ah, yes. So test.c is generated by the test suite to run the littlefs tests. Its presence is useful for debugging why tests have failed. If you do a clean clone of the repo this shouldn't be a problem. I'll see if I can improve the experience though.

**Comment by geky** [comment]
Here we go, I added a step that should remove the test.c file after a successful test run. So normally this shouldn't show up: https://github.com/ARMmbed/littlefs/pull/70

Let me know if this looks good to you
